# Generated by Django 6.0.2 on 2026-04-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='group',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
        migrations.RemoveField(
            model_name='group',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='group',
            name='room',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='student',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='room',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='SpacePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='space_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='ShopHistory',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
