# Generated by Django 6.0.2 on 2026-04-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_remove_attendance_group_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spacepost',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='spacepost',
            name='correct_answer',
            field=models.CharField(default='javob', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spacepost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='space.category'),
        ),
        migrations.AlterField(
            model_name='spacepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
